[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  CI = "false"
  REACT_APP_CI = "false"
  REACT_APP_API_KEY = "f9ed59f4979deb75280b4e170f778992"
  REACT_APP_SERVER_TOKEN ="692d0fe9fcd94adff3c2fde54537b03f7a7efcf91e8a46faff9287f0cff5da83"